kind = "web"
previewPath = "/"
title = "Bank Mondial"
version = "1.0.0"
id = "artifacts/bank-mondial"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20225

[services.development]
run = "pnpm --filter @workspace/bank-mondial run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/bank-mondial", "run", "build" ]
publicDir = "artifacts/bank-mondial/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20225"
BASE_PATH = "/"
